### ISSUE TITLE
Should rotation policy be thread-safe?

### ISSUE THREAD

**Issue by aperepel** [ptgoetz/storm-hdfs#5]
Hi, is rotation policy instantiated per bolt instance? If not, the policy implementation might need a few adjustments to account for concurrent access to non-atomic fields, e.g. here: https://github.com/ptgoetz/storm-hdfs/blob/master/src/main/java/org/apache/storm/hdfs/bolt/rotation/FileSizeRotationPolicy.java#L70

**Comment by ptgoetz** [comment]
Technically it is only _instantiated_ once when the topology is created, but because of the way topologies are (de)serialized, there will be one instance per bolt task. For example, if you set the parallelism hint for the bolt to 3, there will be 3 separate instances.

So no, it does not have to be thread-safe.
